SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `copy`;
DROP TABLE IF EXISTS rent;
DROP TABLE IF EXISTS produce;
DROP TABLE IF EXISTS car;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS user_category;
DROP TABLE IF EXISTS car_category;
SET FOREIGN_KEY_CHECKS=1;